POST http://localhost:3000/api/v1/product/add
Content-Type: application/json

{
    "brand": "Apple",
    "name": "Mac Pro 19inch ",
    "category": "Laptops",
    "location": "Barcelona",
    "price": 1550.95
}

######################################

PATCH http://localhost:3000/api/v1/product/update/1
Content-Type: application/json

response: `This action updates a #${id} product`

#####################################

GET http://localhost:3000/api/v1/product/all
Content-Type: application/json

response: `This action returns all product`

#####################################

GET http://localhost:3000/api/v1/product/1
Content-Type: application/json

response: `This action returns a #${id} product`

#####################################

DELETE http://localhost:3000/api/v1/product/delete/1
Content-Type: application/json

response: `This action removes a #${id} product`

######################################
