POST http://localhost:3000/api/v1/product/add
Content-Type: application/json
######

PATCH http://localhost:3000/api/v1/product/update/1
Content-Type: application/json
######

GET http://localhost:3000/api/v1/product/all
Content-Type: application/json
######

GET http://localhost:3000/api/v1/product/1
Content-Type: application/json
######

DELETE http://localhost:3000/api/v1/product/delete/1
Content-Type: application/json
######